### ISSUE TITLE
How to represent DICOM tag values in NIDM-Exp?

### ISSUE THREAD

**Issue by khelm** [incf-nidash/nidm-specs#392]
In working on the NIDM-Experiment OWL file, the issue of how to represent the various DICOM tag values arose.  @cmaumet @nicholsn and @khelm have been discussing some possibilities, given that the tags are already defined within Neurolex and can be referred to using the appropriate nlx_##### ID.

Here are two possibilities:

(nlx_15077 is 'repetition time')

_In the OWL file:_

```
prov:Entity a owl:Class .
 nlx_15077 a rdfs:subClassOf prov:Entity .
repetition_time_value a owl:DataProperty ;
rdfs:domain  nlx_15077 .
```

_And these in a document:_

```
:instance a nlx_15077 ;
     repetition_time_value "1000.00"^^xsd:float .
```

Another possibility is (here the Neurolex label is used rather than the ID to make things easier to discuss):
_In the ontology:_

```
prov:Entity a owl:Class .

nidm:Map rdfs:subClassOf prov:Entity .
nidm:DICOMProperties rdfs:subClassOf prov:Entity .
nlx:'TR' rdfs:subClassOf prov:Entity .
nlx:'TE' rdfs:subClassOf prov:Entity .

hasDICOMProperties a owl:ObjectProperty .
hasDICOMProperties rdfs:domain nidm:Map .
hasDICOMProperties rdfs:range nidm:DICOMProperties .
```

_In the document:_

```
my_map_id a nidm:Map
my_map_id hasDICOMProperties my_DICOM_properties_id

my_DICOM_properties_id a nidm:DICOMProperties .
my_DICOM_properties_id prov:hasMember my_TR_id .
my_DICOM_properties_id prov:hasMember my_TE_id .

my_TR_id a nlx:'TR'
my_TR_id prov:value 3 .

my_TE_id a nlx:'TE'
my_TE_id prov:value 3 .
```

**Comment by satra** [comment]
instead of creating a property collection for a dicom image why not use the typical foaf like approach:

`curl -H "Accept: text/turtle" https://www.w3.org/People/Berners-Lee/card#i`

example:

```
dicom_map_id hasProperties dicom_properties .
dicom_properties a nidm:DicomProperties;
                  nlx:'TR' 3;
                  nlx :'TE' 30 .
```               

and then define a reification that's equivalent to the previous post.

```
my_TR_id a nlx:'TR'
my_TR_id prov:value 3 .
```

**Comment by cmaumet** [comment]
@satra: For me to understand better what is the typical foaf like approach, could you point to an example of property that show this pattern in the card document?

For the DICOM example, would `nlx:'TR'` be defined both as an `owl:class` and an `owl:dataProperty`?

**Comment by tiborauer** [comment]
@satra: I like your approach. Howerver,  I cannot see why reification is needed and where `my_<nlx label>_id` is used. Why `nlx:'TR' 3;` is not enough?

**Comment by satra** [comment]
@cmaumet:

> For the DICOM example, would `nlx:'TR'` be defined both as an `owl:class` and an `owl:dataProperty`?

i would think `dicom_properties` could be a class and each thing like `nlx:'TR'` could be a property.

so if `dicom_id a nidm:dicom_properties` then `dicom_id some_property some_value` should be ok.

if you take an example below (the `:` is the foaf prefix):

`:family_name` does not point to an `family_name_id` whose value is `'Berners-Lee'`. 

```
card:i     rdf:type :Person;
         ...
         :family_name "Berners-Lee";
         ...
```

@tiborauer - the reification would be needed if we want to conform to `BFO` and define `nlx:'TR'` as both class and property. i don't think we have to.

**Comment by khelm** [comment]
I also thought I would throw into the mix here the method that **@agbeltran** suggested.  First her example:

```
###type defintions
group_id a stato:'study group population'.
group_size_id a stato:'study group population size'.
value_specification_id a obi:'value specification'.

###triples to relate the group and its size, via a 'value specification'
group_id obi:'has quality' group_size_id.
group_size_id obi:'has value specification' value_specification_id.
value_specification_id obi:'has specified value' 18.
```

_and then a version for nlx:'TR':_

```
###type defintions
DICOMTagCollection a prov:'collection'.
TR_id a nlx:'TR".
value_specification_id a obi:'value specification'.

###triples to relate the group and its size, via a 'value specification'
DICOMTagCollection obi:'has quality' TR_id.
TR_id obi:'has value specification' value_specification_id.
value_specification_id obi:'has specified value' 10000.
```

**Comment by cmaumet** [comment]
@satra: that makes sense! As @tiborauer, I was confused by the reification part. 

My proposal was assuming that nlx:'TR', nlx:'TE', etc. were defined as classes (which I beleive is the case right now in NeuroLex) but I would be happy to see them defined as data properties.

As @khelm is pointed out this goes back to the class vs. property discussion (cf. also https://github.com/ISA-tools/stato/issues/38 for a similar discussion with STATO).

**Comment by khelm** [comment]
Then we would define nidm:'TR' as a property, but point to the class nlx:'TR' for the definition?

**Comment by nicholsn** [comment]
@khelm, this is similar to what they do in the data cube vocabulary. For example, you can define a new property that references a concept from an ontology like so:

```
nidm:'TR' a DataProperty ;
    rdfs:label "Repetition Time" ;
    qb:concept nlx:'TR' .
```

One thing to consider is that, per [rdfs vs owl](http://www.cambridgesemantics.com/semantic-university/rdfs-vs-owl) under the section on 'Rigidity', in OWL a URI cannot be both an Instance of a Class and also a Class. Does anyone know if all properties are considered instances?

**Comment by cmaumet** [comment]
@khelm: I think you have now make a decision on this and started up the DICOM ontology at https://github.com/incf-nidash/dicom-ontology. Do you think we can now close the current issue? Thanks!

**Comment by khelm** [comment]
I thought I would revive this discussion since @dbkeator were just talking about how to represent units, which will also have an impact on this discussion.

Taking a cue from Satra above: first define the tags as a collection of properties and then the individual DICOM tags would be Datatype Properties like so?:
``` 
nidm:DICOMtag a prov:Collection ; 
   dicm:'TE' a nidmDICOMtag .
```
then
```
id:123456789 a nidm:AcquisitionObject ;
           dicm:'TE'  "5.0"xsd:float ; 
```

**Comment by khelm** [comment]
Currently we are modeling DICOM tags as datatype properties.
