### ISSUE TITLE
Define TFCE, cluster mass in NIDM Results

### ISSUE THREAD

**Issue by nicholst** [incf-nidash/nidm-specs#455]
Motivated by extending NIDM-Results to nonparametric inference produce by FSL's randomise, we need to add additional types of inference:

- [ ] Cluster mass
- [ ] Threshold-Free Cluster Enhancement (TFCE)

TFCE will require defining 2 parameters, the height power `H` and the extent power `E`.

**Comment by cmaumet** [comment]
Thanks @nicholst! Part of this (in particular TFCE) is addressed by https://github.com/incf-nidash/nidm-specs/pull/233.

**Comment by nicholst** [comment]
Oh!  This issue is redundant.  Closing...
