### ISSUE TITLE
Create a 'term status' page for NIDM-experiment

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidm-specs#462]
Similarly to the term status page we have for NIDM-Results at: https://github.com/incf-nidash/nidm-specs/tree/master/nidm/nidm-results/terms:

![screen shot 2018-04-23 at 10 06 53](https://user-images.githubusercontent.com/5374264/39114091-126e5d36-46de-11e8-8fc7-690177dc99e3.png)

we would like to create a term status page for NIDM-experiment at https://github.com/incf-nidash/nidm-specs/tree/master/nidm/nidm-experiment/terms.

This could be done by adapting the code in `UpdateTermReadme` to use the NIDM-experiment owl file. 

Help on this would be greatly appreciated.

**Comment by khelm** [comment]
Hi @cmaumet  - I will look into this.

**Comment by cmaumet** [comment]
👍  Thanks @khelm!

**Comment by khelm** [comment]
This has been completed:
https://github.com/incf-nidash/nidm-specs/tree/master/nidm/nidm-experiment/terms
