### ISSUE TITLE
Should imported terms be displayed in the NIDM-Experiment Specs page?

### ISSUE THREAD

**Issue by khelm** [incf-nidash/nidm-specs#476]
Currently the NIDM-Experiment Specs page [here](http://nidm.nidash.org/specs/nidm-experiment_dev.html) shows only the NIDM and ontoneurolog-instruments terms (and only to a certain graph depth), but there are terms imported from many more ontologies such as SIO, PATO, QIBO, etc. Should we display the entire graph on this page?  I am in favor of this as this would be a way for potential users to see the whole graph without having to load the ontology file in Protege or an RDF viewer.  Anyone have any thoughts on this?

**Comment by cmaumet** [comment]
Yes, I also think it's good to have a high level view of the full graph! Maybe the external terms (or some of them) could appear in the textual spec description rather than in the main chart?

**Comment by khelm** [comment]
I'm going to close this  issue since we're now working on an expandable hierarchy viewer that will include the imported terms.
