### ISSUE TITLE
Travis Tests failing due to jsonld.py

### ISSUE THREAD

**Issue by khelm** [incf-nidash/nidm-specs#491]
@dbkeator @cmaumet - The latest code fixes that I've pushed have failed for reasons that don't seem to have anything to do with the fixes I've made.  The issue seems to be with a syntax error in jsonld.py.  It fails in six different places all seemingly related to nidm-results, but all are the same call to jsonld.py

The Travis report is [here](https://travis-ci.org/github/incf-nidash/nidm-specs/builds/676974651) 

Any ideas?

**Comment by khelm** [comment]
Also, I've locally run create_expe_specifications.py and refresh.py and neither returned any errors.

**Comment by cmaumet** [comment]
Hi @khelm! Yes, the problem was not related to your edits. The error was an effect of the (different) versions of the libraries pyld and rdflib-jsonld used by Travis. I've added two commits to force older versions and now the tests pass at https://github.com/incf-nidash/nidm-specs/pull/490.

**Comment by khelm** [comment]
Thanks very much @cmaumet, I appreciate you looking into this!  I will re-run the tests on my last commit.

**Comment by cmaumet** [comment]
Hi @khelm! Happy to help :) I don't know if you have seen but in order to test, I've added commits directly into your branch (cf. https://github.com/incf-nidash/nidm-specs/pull/490). You will need to pull these first. Provided that `origin` points to your fork, you could use:
```
git pull origin update_exp_specs_file
```

**Comment by khelm** [comment]
Hi @cmaumet , thanks I will test this out today.

**Comment by khelm** [comment]
@cmaumet and @dbkeator - Travis checks now run successfully and all latest work has been merged.  Thanks!
